-- Generated by bft-maker
-- Load source data

CREATE OR REPLACE TABLE "customers" AS
SELECT * FROM read_csv_auto('/home/matthew/bft-maker/data/saas-billing/customers.csv');

CREATE OR REPLACE TABLE "plans" AS
SELECT * FROM read_csv_auto('/home/matthew/bft-maker/data/saas-billing/plans.csv');

CREATE OR REPLACE TABLE "months" AS
SELECT * FROM read_csv_auto('/home/matthew/bft-maker/data/saas-billing/months.csv');

CREATE OR REPLACE TABLE "subscriptions" AS
SELECT * FROM read_csv_auto('/home/matthew/bft-maker/data/saas-billing/subscriptions.csv');

CREATE OR REPLACE TABLE "billings" AS
SELECT * FROM read_csv_auto('/home/matthew/bft-maker/data/saas-billing/billings.csv');
