-- customer_plan_monthly.sql
-- Generated by bft-maker
-- BFT table: Customer x Plan x Month
-- Metrics:
--   annual_contract_value (Customer) allocation for Plan, reserve for Month
--   mrr (Subscription) reserve for Month
--   seat_count (Subscription) reserve for Month
--   monthly_rate (Plan) sum_over_sum for Customer, reserve for Month
--   amount_billed (Billing) elimination for Plan
--   amount_paid (Billing) allocation for Plan

-----------------------------------------------------------------------
-- Step 1: Base grain (Customer x Plan x Month)
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "cpm_base" AS
SELECT
    c."customer_id",
    c."name" AS "customer_name",
    c."annual_contract_value",
    p."plan_id",
    p."name" AS "plan_name",
    p."monthly_rate",
    m."month_id",
    m."month_label" AS "month_name",
    m."month_date",
    s."mrr",
    s."seat_count",
    b."amount_billed",
    b."amount_paid"
FROM "customers" c
JOIN "subscriptions" s ON c."customer_id" = s."customer_id"
JOIN "plans" p ON p."plan_id" = s."plan_id"
JOIN "billings" b ON c."customer_id" = b."customer_id"
JOIN "months" m ON m."month_id" = b."month_id";

-----------------------------------------------------------------------
-- Step 2: Compute weights for allocation / sum_over_sum
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "cpm_weighted" AS
SELECT
    *,
    COUNT(DISTINCT "plan_id") OVER (PARTITION BY "customer_id") AS "subscription_count"
FROM "cpm_base";

-----------------------------------------------------------------------
-- Step 3: Assemble final table
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "customer_plan_monthly" AS

-- base rows
SELECT
    "customer_id",
    "customer_name",
    "plan_id",
    "plan_name",
    "month_id",
    "month_name",
    0.0 AS "annual_contract_value",
    0.0 AS "mrr",
    0.0 AS "seat_count",
    "monthly_rate",
    1.0 / "subscription_count" AS "monthly_rate_weight",
    "amount_billed" * 1.0 AS "amount_billed",
    "amount_paid" * 1.0 / "subscription_count" AS "amount_paid"
FROM "cpm_weighted"

UNION ALL

-- annual_contract_value propagation data rows
SELECT DISTINCT
    "customer_id",
    "customer_name",
    "plan_id",
    "plan_name",
    NULL AS "month_id",
    '<Unallocated>' AS "month_name",
    "annual_contract_value" * 1.0 / "subscription_count" AS "annual_contract_value",
    0.0 AS "mrr",
    0.0 AS "seat_count",
    0.0 AS "monthly_rate",
    0 AS "monthly_rate_weight",
    0.0 AS "amount_billed",
    0.0 AS "amount_paid"
FROM "cpm_weighted"

UNION ALL

-- Reserve placeholder rows for mrr and seat_count
SELECT
    s."customer_id",
    c."name" AS "customer_name",
    NULL AS "plan_id",
    '<Unallocated>' AS "plan_name",
    NULL AS "month_id",
    '<Unallocated>' AS "month_name",
    0.0 AS "annual_contract_value",
    SUM(s."mrr") * 1.0 AS "mrr",
    SUM(s."seat_count") * 1.0 AS "seat_count",
    0.0 AS "monthly_rate",
    0 AS "monthly_rate_weight",
    0.0 AS "amount_billed",
    0.0 AS "amount_paid"
FROM "subscriptions" s
JOIN "customers" c ON s."customer_id" = c."customer_id"
GROUP BY s."customer_id", c."name"

UNION ALL

-- amount_billed elimination correction (hop 0)
SELECT
    "customer_id",
    "customer_name",
    NULL AS "plan_id",
    '<Unallocated>' AS "plan_name",
    "month_id",
    "month_name",
    0 AS "annual_contract_value",
    0 AS "mrr",
    0 AS "seat_count",
    0 AS "monthly_rate",
    0 AS "monthly_rate_weight",
    "amount_billed" * (1 - COUNT(DISTINCT "plan_id")) AS "amount_billed",
    0 AS "amount_paid"
FROM "cpm_base"
GROUP BY "customer_id", "customer_name", "month_id", "month_name", "amount_billed";

-----------------------------------------------------------------------
-- Validation
-----------------------------------------------------------------------

-- V1: SUM(annual_contract_value) matches source
SELECT 'V1 annual_contract_value_sum' AS test,
       CASE WHEN ABS(SUM("annual_contract_value") - (SELECT SUM("annual_contract_value") FROM "customers")) < 0.01
            THEN 'PASS' ELSE 'FAIL: ' || SUM("annual_contract_value") END AS result
FROM "customer_plan_monthly";

-- V2: SUM(mrr) matches source
SELECT 'V2 mrr_sum' AS test,
       CASE WHEN ABS(SUM("mrr") - (SELECT SUM("mrr") FROM "subscriptions")) < 0.01
            THEN 'PASS' ELSE 'FAIL: ' || SUM("mrr") END AS result
FROM "customer_plan_monthly";

-- V3: SUM(seat_count) matches source
SELECT 'V3 seat_count_sum' AS test,
       CASE WHEN ABS(SUM("seat_count") - (SELECT SUM("seat_count") FROM "subscriptions")) < 0.01
            THEN 'PASS' ELSE 'FAIL: ' || SUM("seat_count") END AS result
FROM "customer_plan_monthly";

-- V4: SUM(amount_billed) matches source
SELECT 'V4 amount_billed_sum' AS test,
       CASE WHEN ABS(SUM("amount_billed") - (SELECT SUM("amount_billed") FROM "billings")) < 0.01
            THEN 'PASS' ELSE 'FAIL: ' || SUM("amount_billed") END AS result
FROM "customer_plan_monthly";

-- V5: SUM(amount_paid) matches source
SELECT 'V5 amount_paid_sum' AS test,
       CASE WHEN ABS(SUM("amount_paid") - (SELECT SUM("amount_paid") FROM "billings")) < 0.01
            THEN 'PASS' ELSE 'FAIL: ' || SUM("amount_paid") END AS result
FROM "customer_plan_monthly";