-- customer_plan_summary.sql
-- Generated by bft-maker
-- BFT table: Customer x Plan
-- Metrics:
--   annual_contract_value (Customer) allocation for Plan
--   mrr (Subscription) 
--   seat_count (Subscription) 
--   amount_billed (Billing) elimination for Plan
--   amount_paid (Billing) allocation for Plan

-----------------------------------------------------------------------
-- Step 1: Base grain (Customer x Plan)
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "cps_base" AS
SELECT
    c."customer_id",
    c."name" AS "customer_name",
    c."annual_contract_value",
    p."plan_id",
    p."name" AS "plan_name",
    s."mrr",
    s."seat_count"
FROM "customers" c
JOIN "subscriptions" s ON c."customer_id" = s."customer_id"
JOIN "plans" p ON p."plan_id" = s."plan_id";

-----------------------------------------------------------------------
-- Step 2: Compute weights for allocation / sum_over_sum
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "cps_weighted" AS
SELECT
    *,
    COUNT(DISTINCT "plan_id") OVER (PARTITION BY "customer_id") AS "subscription_count"
FROM "cps_base";

-----------------------------------------------------------------------
-- Step 1: Base grain (Customer x Month x Plan)
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "cps_g1_base" AS
SELECT
    c."customer_id",
    c."name" AS "customer_name",
    m."month_id",
    m."month_label" AS "month_name",
    p."plan_id",
    p."name" AS "plan_name",
    b."amount_billed",
    b."amount_paid"
FROM "customers" c
JOIN "subscriptions" s ON c."customer_id" = s."customer_id"
JOIN "plans" p ON p."plan_id" = s."plan_id"
JOIN "billings" b ON c."customer_id" = b."customer_id"
JOIN "months" m ON m."month_id" = b."month_id";

-----------------------------------------------------------------------
-- Step 2: Compute weights for allocation / sum_over_sum
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "cps_g1_weighted" AS
SELECT
    *,
    COUNT(DISTINCT "plan_id") OVER (PARTITION BY "customer_id", "month_id") AS "subscription_count"
FROM "cps_g1_base";

-----------------------------------------------------------------------
-- Step 2.5: Summarize to BFT grain (Customer x Plan)
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "cps_g1_summarized" AS
SELECT
    "customer_id",
    "customer_name",
    "plan_id",
    "plan_name",
    SUM("amount_billed" * 1.0) AS "amount_billed",
    SUM("amount_paid" * 1.0 / "subscription_count") AS "amount_paid"
FROM "cps_g1_weighted"
GROUP BY "customer_id", "customer_name", "plan_id", "plan_name";

-----------------------------------------------------------------------
-- Step 3: Assemble final table
-----------------------------------------------------------------------
CREATE OR REPLACE TABLE "customer_plan_summary" AS

-- bft base rows
SELECT
    "customer_id",
    "customer_name",
    "plan_id",
    "plan_name",
    "annual_contract_value" * 1.0 / "subscription_count" AS "annual_contract_value",
    "mrr" * 1.0 AS "mrr",
    "seat_count" * 1.0 AS "seat_count",
    0.0 AS "amount_billed",
    0.0 AS "amount_paid"
FROM "cps_weighted"

UNION ALL

-- g1 base rows
SELECT
    "customer_id",
    "customer_name",
    "plan_id",
    "plan_name",
    0.0 AS "annual_contract_value",
    0.0 AS "mrr",
    0.0 AS "seat_count",
    "amount_billed",
    "amount_paid"
FROM "cps_g1_summarized";

-----------------------------------------------------------------------
-- Validation
-----------------------------------------------------------------------

-- V1: SUM(annual_contract_value) matches source
SELECT 'V1 annual_contract_value_sum' AS test,
       CASE WHEN ABS(SUM("annual_contract_value") - (SELECT SUM("annual_contract_value") FROM "customers")) < 0.01
            THEN 'PASS' ELSE 'FAIL: ' || SUM("annual_contract_value") END AS result
FROM "customer_plan_summary";

-- V2: SUM(amount_billed) matches source
SELECT 'V2 amount_billed_sum' AS test,
       CASE WHEN ABS(SUM("amount_billed") - (SELECT SUM("amount_billed") FROM "billings")) < 0.01
            THEN 'PASS' ELSE 'FAIL: ' || SUM("amount_billed") END AS result
FROM "customer_plan_summary";

-- V3: SUM(amount_paid) matches source
SELECT 'V3 amount_paid_sum' AS test,
       CASE WHEN ABS(SUM("amount_paid") - (SELECT SUM("amount_paid") FROM "billings")) < 0.01
            THEN 'PASS' ELSE 'FAIL: ' || SUM("amount_paid") END AS result
FROM "customer_plan_summary";