#!/bin/bash
# Generated by bft-maker
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Running BFT SQL..."
python3 - "$SCRIPT_DIR" <<'PYEOF'
import duckdb, os, sys

script_dir = sys.argv[1]
con = duckdb.connect()
files = [os.path.join(script_dir, '00_load_data.sql'), os.path.join(script_dir, '01_customer_plan_monthly.sql'), os.path.join(script_dir, '02_customer_plan_summary.sql')]
all_pass = True
for f in files:
    print(f'\n=== {f} ===')
    sql = open(f).read()
    for stmt in [s.strip() for s in sql.split(';') if s.strip()]:
        lines = [l for l in stmt.split('\n') if l.strip() and not l.strip().startswith('--')]
        if not lines:
            continue
        result = con.execute(stmt)
        if lines[0].strip().split()[0].upper() == 'SELECT':
            for row in result.fetchall():
                cols = [d[0] for d in result.description]
                d = dict(zip(cols, row))
                status = 'PASS' if 'PASS' in str(d.get('result', '')) else 'FAIL'
                if status == 'FAIL':
                    all_pass = False
                print(f"  {d['test']}: {d['result']}")
print()
if all_pass:
    print('All validations passed.')
else:
    print('SOME VALIDATIONS FAILED')
    sys.exit(1)
PYEOF
