import type { Manifest } from "../manifest/types.js";
import type {
  TablePlan,
  TimePlan,
  MetricPlan,
  DimensionStrategy,
  SourceMapping,
  GeneratedOutput,
  GrainGroup,
  JoinLink,
} from "./types.js";
import { defaultSourceMapping } from "./planner.js";
import { planAll } from "./planner.js";

export interface GenerateOptions {
  sourceMapping?: SourceMapping;
  /** Directory containing source CSV files (used in load SQL). Default: "." */
  dataDir?: string;
}

/** Quote a SQL identifier with DuckDB double-quote style. */
function q(identifier: string): string {
  return `"${identifier.replace(/"/g, '""')}"`;
}

/**
 * Generate all SQL for a manifest.
 */
export function generate(manifest: Manifest, options?: GenerateOptions): GeneratedOutput {
  const sm = options?.sourceMapping ?? defaultSourceMapping(manifest);
  const dataDir = options?.dataDir ?? ".";
  const plans = planAll(manifest, sm);
  checkPrefixCollisions(plans);

  const loadDataSQL = generateLoadData(manifest, sm, dataDir);
  const tables = plans.map((plan) => ({
    name: plan.tableName,
    sql: generateTableSQL(plan, manifest, sm),
  }));
  const runScript = generateRunScript(tables.map((t) => t.name));

  return { loadDataSQL, tables, runScript };
}

// ---------------------------------------------------------------------------
// Load data
// ---------------------------------------------------------------------------

function generateLoadData(manifest: Manifest, sm: SourceMapping, dataDir: string): string {
  const lines = ["-- Generated by bft-maker", "-- Load source data\n"];
  for (const entity of manifest.entities) {
    const es = sm.entities[entity.name];
    lines.push(
      `CREATE OR REPLACE TABLE ${q(es.table)} AS`,
      `SELECT * FROM read_csv_auto('${dataDir}/${es.table}.csv');\n`
    );
  }
  for (const rel of manifest.relationships) {
    const rs = sm.relationships[rel.name];
    lines.push(
      `CREATE OR REPLACE TABLE ${q(rs.table)} AS`,
      `SELECT * FROM read_csv_auto('${dataDir}/${rs.table}.csv');\n`
    );
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Per-table SQL
// ---------------------------------------------------------------------------

function generateTableSQL(plan: TablePlan, manifest: Manifest, sm: SourceMapping): string {
  const sections: string[] = [];
  const prefix = tablePrefix(plan.tableName);
  const rawLabel = manifest.placeholder_labels?.reserve ?? "<Unallocated>";
  const label = rawLabel.replace(/'/g, "''");
  const allMetrics = plan.grainGroups.flatMap((g) => g.metrics);

  sections.push(headerComment(plan, sm));

  // Split groups into BFT-grain (no summarization) and summarization groups.
  // Non-summarization groups share one pipeline at BFT grain because their
  // compute grains are subsets of the BFT grain — the base join includes all
  // entities, and per-metric weights are computed from the shared base table.
  const bftGroups = plan.grainGroups.filter((g) => !g.needsSummarization);
  const sumGroups = plan.grainGroups.filter((g) => g.needsSummarization);
  const bftMetrics = bftGroups.flatMap((g) => g.metrics);

  if (sumGroups.length === 0) {
    // All metrics at BFT grain: merge groups into one standard pipeline
    const mergedGroup: GrainGroup = {
      id: "g0",
      grain: plan.bftGrain,
      joinChain: plan.bftJoinChain,
      metrics: bftMetrics,
      needsSummarization: false,
    };
    sections.push(baseJoinSQL(plan.bftGrain, plan.bftJoinChain, allMetrics, sm, prefix, plan.timePlan));
    sections.push(weightedSQL(mergedGroup, sm, prefix));
    sections.push(assemblySQL(plan, allMetrics, sm, prefix, label));
  } else if (bftMetrics.length === 0) {
    // All metrics need summarization
    if (sumGroups.length === 1) {
      // Single summarization group: standard summarization pipeline
      const group = sumGroups[0];
      sections.push(baseJoinSQL(group.grain, group.joinChain, allMetrics, sm, prefix, plan.timePlan));
      sections.push(weightedSQL(group, sm, prefix));
      sections.push(summarizationSQL(plan, group, allMetrics, sm, prefix));
      sections.push(assemblySQL(plan, allMetrics, sm, prefix, label));
    } else {
      // Multiple summarization groups: per-group pipelines + combined assembly
      for (const group of sumGroups) {
        const gPrefix = `${prefix}_${group.id}`;
        sections.push(baseJoinSQL(group.grain, group.joinChain, group.metrics, sm, gPrefix, plan.timePlan));
        sections.push(weightedSQL(group, sm, gPrefix));
        sections.push(summarizationSQL(plan, group, group.metrics, sm, gPrefix));
      }
      sections.push(multiGroupAssemblySQL(plan, allMetrics, bftMetrics, sumGroups, sm, prefix, label));
    }
  } else {
    // Mixed: BFT-grain pipeline + summarization group pipelines + combined assembly
    const mergedBftGroup: GrainGroup = {
      id: "bft",
      grain: plan.bftGrain,
      joinChain: plan.bftJoinChain,
      metrics: bftMetrics,
      needsSummarization: false,
    };
    sections.push(baseJoinSQL(plan.bftGrain, plan.bftJoinChain, bftMetrics, sm, prefix, plan.timePlan));
    sections.push(weightedSQL(mergedBftGroup, sm, prefix));
    for (const group of sumGroups) {
      const gPrefix = `${prefix}_${group.id}`;
      sections.push(baseJoinSQL(group.grain, group.joinChain, group.metrics, sm, gPrefix, plan.timePlan));
      sections.push(weightedSQL(group, sm, gPrefix));
      sections.push(summarizationSQL(plan, group, group.metrics, sm, gPrefix));
    }
    sections.push(multiGroupAssemblySQL(plan, allMetrics, bftMetrics, sumGroups, sm, prefix, label));
  }

  sections.push(validationSQL(plan, allMetrics, sm));

  return sections.join("\n\n");
}

function tablePrefix(tableName: string): string {
  // student_experience → se, department_financial → df
  return tableName
    .split("_")
    .map((w) => w[0])
    .join("");
}

/** Verify no two tables produce the same intermediate-table prefix. */
function checkPrefixCollisions(plans: TablePlan[]): void {
  const seen = new Map<string, string>();
  for (const plan of plans) {
    const prefix = tablePrefix(plan.tableName);
    const existing = seen.get(prefix);
    if (existing) {
      throw new Error(
        `Table prefix collision: "${existing}" and "${plan.tableName}" both produce prefix "${prefix}". Rename one table to avoid ambiguous intermediate tables.`
      );
    }
    seen.set(prefix, plan.tableName);
  }
}

// ---------------------------------------------------------------------------
// Header comment
// ---------------------------------------------------------------------------

function headerComment(plan: TablePlan, sm: SourceMapping): string {
  const lines = [`-- ${plan.tableName}.sql`, `-- Generated by bft-maker`];
  lines.push(`-- BFT table: ${plan.bftGrain.join(" x ")}`);
  lines.push(`-- Metrics:`);
  const allMetrics = plan.grainGroups.flatMap((g) => g.metrics);
  for (const m of allMetrics) {
    const dimDesc = m.propagatedDimensions
      .map((d) => `${d.strategy} for ${d.entity}`)
      .join(", ");
    lines.push(`--   ${m.name} (${m.home.name}) ${dimDesc}`);
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Step 1: Base grain join
// ---------------------------------------------------------------------------

/**
 * Build collision-free single-letter aliases for a set of names.
 * Uses first letter of lowercase name; appends digits on collision.
 */
function buildAliasMap(names: string[]): Map<string, string> {
  const result = new Map<string, string>();
  const used = new Set<string>();
  for (const name of names) {
    let alias = name.toLowerCase().slice(0, 1);
    if (used.has(alias)) {
      let i = 2;
      while (used.has(alias + i)) i++;
      alias = alias + i;
    }
    used.add(alias);
    result.set(name, alias);
  }
  return result;
}

/** Get the primary home entity for a metric (first grain entity). */
function homeEntity(metric: MetricPlan): string {
  return metric.home.grain[0];
}

function baseJoinSQL(
  grainEntities: string[],
  joinChain: JoinLink[],
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string,
  timePlan?: TimePlan,
): string {
  // Build collision-free aliases for all entities and relationships in the query
  const allNames = [...grainEntities, ...joinChain.map((l) => l.relationship)];
  const aliasMap = buildAliasMap(allNames);

  const firstEntity = grainEntities[0];
  const fe = sm.entities[firstEntity];
  const firstAlias = aliasMap.get(firstEntity)!;

  // Track which junction tables are used (for relationship metrics)
  const junctionAliasMap = new Map<string, string>();

  // SELECT columns
  const selectCols: string[] = [];
  for (const entityName of grainEntities) {
    const es = sm.entities[entityName];
    const alias = aliasMap.get(entityName)!;
    selectCols.push(`${alias}.${q(es.idColumn)}`);
    selectCols.push(`${alias}.${q(es.labelColumn)} AS ${q(entityName.toLowerCase() + "_name")}`);
    // Entity metrics
    const entityMetrics = allMetrics.filter(
      (m) => m.home.kind === "entity" && m.home.grain[0] === entityName
    );
    for (const m of entityMetrics) {
      if (m.sourceColumn !== m.name) {
        selectCols.push(`${alias}.${q(m.sourceColumn)} AS ${q(m.name)}`);
      } else {
        selectCols.push(`${alias}.${q(m.name)}`);
      }
    }
  }

  // Include time column for stock metric weighting in summarizationSQL.
  // No collision risk: time column (e.g. month_date) is distinct from the
  // entity id/label scheme ({entity}_id, {entity}_name).
  // Survives to summarization via weightedSQL's SELECT *.
  if (timePlan && grainEntities.includes(timePlan.entity) && allMetrics.some((m) => m.stock)) {
    const timeAlias = aliasMap.get(timePlan.entity);
    if (timeAlias) {
      selectCols.push(`${timeAlias}.${q(timePlan.column)}`);
    }
  }

  // JOIN chain — build it and collect junction aliases
  const joinLines: string[] = [];

  for (const link of joinChain) {
    const jAlias = aliasMap.get(link.relationship)!;
    const toAlias = aliasMap.get(link.toEntity)!;
    junctionAliasMap.set(link.relationship, jAlias);

    const fromAlias = aliasMap.get(link.fromEntity)!;
    joinLines.push(
      `JOIN ${q(link.junctionTable)} ${jAlias} ON ${fromAlias}.${q(sm.entities[link.fromEntity].idColumn)} = ${jAlias}.${q(link.fromColumn)}`
    );
    const toEs = sm.entities[link.toEntity];
    joinLines.push(
      `JOIN ${q(toEs.table)} ${toAlias} ON ${toAlias}.${q(toEs.idColumn)} = ${jAlias}.${q(link.toColumn)}`
    );
  }

  // Relationship metrics — select from junction table alias
  for (const m of allMetrics) {
    if (m.home.kind === "relationship") {
      const jAlias = junctionAliasMap.get(m.home.name);
      if (jAlias) {
        if (m.sourceColumn !== m.name) {
          selectCols.push(`${jAlias}.${q(m.sourceColumn)} AS ${q(m.name)}`);
        } else {
          selectCols.push(`${jAlias}.${q(m.name)}`);
        }
      }
    }
  }

  return [
    `${"-".repeat(71)}`,
    `-- Step 1: Base grain (${grainEntities.join(" x ")})`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${q(prefix + "_base")} AS`,
    `SELECT`,
    selectCols.map((c) => `    ${c}`).join(",\n"),
    `FROM ${q(fe.table)} ${firstAlias}`,
    joinLines.join("\n") + ";",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Step 2: Weights (window functions for allocation / sum_over_sum)
// ---------------------------------------------------------------------------

function weightedSQL(group: GrainGroup, sm: SourceMapping, prefix: string): string {
  const weightExprs = collectWeights(group, sm);
  if (weightExprs.length === 0) {
    // No weights needed — just alias base as weighted
    return [
      `${"-".repeat(71)}`,
      `-- Step 2: No weights needed`,
      `${"-".repeat(71)}`,
      `CREATE OR REPLACE TABLE ${q(prefix + "_weighted")} AS`,
      `SELECT * FROM ${q(prefix + "_base")};`,
    ].join("\n");
  }

  return [
    `${"-".repeat(71)}`,
    `-- Step 2: Compute weights for allocation / sum_over_sum`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${q(prefix + "_weighted")} AS`,
    `SELECT`,
    `    *,`,
    weightExprs.map((w) => `    ${w.expr} AS ${q(w.name)}`).join(",\n"),
    `FROM ${q(prefix + "_base")};`,
  ].join("\n");
}

interface WeightExpr {
  name: string;
  expr: string;
}

function collectWeights(group: GrainGroup, sm: SourceMapping): WeightExpr[] {
  const weights: WeightExpr[] = [];
  const seen = new Set<string>();

  for (const metric of group.metrics) {
    // Get all propagated dimensions (with hopIndex) sorted by hop order.
    // This includes elimination hops — we need them for partition columns
    // even though we only generate weights for allocation/sum_over_sum hops.
    const allHops = metric.propagatedDimensions
      .filter((d) => d.hopIndex !== undefined)
      .sort((a, b) => (a.hopIndex ?? 0) - (b.hopIndex ?? 0));

    const allocDims = allHops.filter(
      (d) => d.strategy === "allocation" || d.strategy === "sum_over_sum"
    );

    if (allocDims.length === 0) continue;

    const homePartitionCols = metric.home.grain.map((e) => q(sm.entities[e].idColumn));

    for (const dim of allocDims) {
      const weightName = `${dim.relationship.toLowerCase()}_count`;
      if (seen.has(weightName)) continue;
      seen.add(weightName);

      // Partition by home + all entities from prior hops (any strategy)
      const partitionCols = [...homePartitionCols];
      for (const priorDim of allHops) {
        if ((priorDim.hopIndex ?? 0) >= (dim.hopIndex ?? 0)) break;
        partitionCols.push(q(sm.entities[priorDim.entity].idColumn));
      }

      const targetEs = sm.entities[dim.entity];
      weights.push({
        name: weightName,
        expr: `COUNT(DISTINCT ${q(targetEs.idColumn)}) OVER (PARTITION BY ${partitionCols.join(", ")})`,
      });
    }
  }

  return weights;
}

// ---------------------------------------------------------------------------
// Step 2.5: Summarization (GROUP BY to remove non-BFT entities)
// ---------------------------------------------------------------------------

function summarizationSQL(
  plan: TablePlan,
  group: GrainGroup,
  metrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string
): string {
  // GROUP BY BFT grain entities that are in this group's compute grain.
  // (For single-group tables, this is all BFT entities. For multi-group,
  // some BFT entities may be reserve dimensions not in this group's grain.)
  const groupGrainSet = new Set(group.grain);
  const bftEntitiesInGrain = plan.bftGrain.filter((e) => groupGrainSet.has(e));

  const groupByCols: string[] = [];
  const selectCols: string[] = [];

  for (const entityName of bftEntitiesInGrain) {
    const es = sm.entities[entityName];
    const nameCol = q(entityName.toLowerCase() + "_name");
    groupByCols.push(q(es.idColumn));
    groupByCols.push(nameCol);
    selectCols.push(q(es.idColumn));
    selectCols.push(nameCol);
  }

  // Determine if we're summarizing out a time-derived entity
  const bftGrainSet = new Set(bftEntitiesInGrain);
  const summarizedEntities = group.grain.filter((e) => !bftGrainSet.has(e));
  const summarizingTime = plan.timePlan != null &&
    summarizedEntities.some((e) => plan.timePlan!.timeDerivedEntities.has(e));

  // Metric expressions: SUM with allocation weights where applicable
  for (const metric of metrics) {
    if (metric.nature === "non-additive") {
      selectCols.push(`SUM(${q(metric.name)}) AS ${q(metric.name)}`);
      selectCols.push(`SUM(${sumOverSumWeightExpr(metric)}) AS ${q(metric.name + "_weight")}`);
    } else if (metric.stock && summarizingTime) {
      // Stock metric with time being summarized out: use weighted average
      const tp = plan.timePlan!;
      if (tp.weighting === "equal") {
        selectCols.push(`AVG(${allocationExpr(metric, sm)}) AS ${q(metric.name)}`);
      } else {
        // dateCol is only referenced inside SUM(), so it's evaluated per-row
        // before aggregation — valid SQL even though it's not in GROUP BY.
        const dateCol = q(tp.column);
        const weight = `DATE_DIFF('day', ${dateCol}, ${dateCol} + ${tp.interval})`;
        selectCols.push(`SUM(${allocationExpr(metric, sm)} * ${weight}) / SUM(${weight}) AS ${q(metric.name)}`);
      }
    } else {
      // allocationExpr returns "metric * 1.0" for non-allocated metrics,
      // "metric * 1.0 / weight" for allocated ones — handles all additive cases.
      selectCols.push(`SUM(${allocationExpr(metric, sm)}) AS ${q(metric.name)}`);
    }
  }

  return [
    `${"-".repeat(71)}`,
    `-- Step 2.5: Summarize to BFT grain (${bftEntitiesInGrain.join(" x ")})`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${q(prefix + "_summarized")} AS`,
    `SELECT`,
    selectCols.map((c) => `    ${c}`).join(",\n"),
    `FROM ${q(prefix + "_weighted")}`,
    `GROUP BY ${groupByCols.join(", ")};`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Step 3: Assembly (UNION ALL of base grain + placeholder branches)
// ---------------------------------------------------------------------------

function assemblySQL(
  plan: TablePlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string,
  placeholderLabel: string
): string {
  const branches: string[] = [];

  // Determine source table for base grain rows
  const hasSummarization = plan.grainGroups.some((g) => g.needsSummarization);
  const sourceTable = hasSummarization ? `${prefix}_summarized` : `${prefix}_weighted`;

  // Branch A: base grain rows
  const baseGroup: GrainGroup = {
    id: "base",
    grain: plan.bftGrain,
    joinChain: plan.bftJoinChain,
    metrics: allMetrics,
    needsSummarization: hasSummarization,
  };
  branches.push(groupBaseBranch(plan, baseGroup, allMetrics, sm, sourceTable, placeholderLabel));

  // Placeholder branches for each metric (only when no summarization —
  // summarized tables already have the correct aggregation)
  if (!hasSummarization) {
    for (const metric of allMetrics) {
      if (metric.nature === "non-additive") continue;

      const hasElimDims = metric.propagatedDimensions.some((d) => d.strategy === "elimination");
      const hasAllocDims = metric.propagatedDimensions.some((d) => d.strategy === "allocation");
      const hasReserveDims = metric.reserveDimensions.length > 0;
      const hasPropagation = hasElimDims || hasAllocDims;

      if (!hasPropagation && !hasReserveDims) continue;

      if (hasReserveDims) {
        if (hasPropagation) {
          branches.push(propagationDataBranch(plan, metric, allMetrics, sm, prefix, placeholderLabel));
        } else {
          branches.push(reserveBranch(plan, metric, allMetrics, sm, placeholderLabel));
        }
      }

      if (hasElimDims) {
        const elimDims = metric.propagatedDimensions.filter((d) => d.strategy === "elimination");
        for (const elimDim of elimDims) {
          branches.push(elimCorrectionBranch(plan, metric, elimDim, allMetrics, sm, prefix, placeholderLabel));
        }
      }
    }
  }

  const unionAll = branches.join("\n\nUNION ALL\n\n");

  return [
    `${"-".repeat(71)}`,
    `-- Step 3: Assemble final table`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${q(plan.tableName)} AS`,
    "",
    unionAll + ";",
  ].join("\n");
}

/**
 * Assembly for tables with mixed BFT-grain and summarization groups.
 * BFT-grain metrics come from `prefix_weighted`, placeholder branches as usual.
 * Summarization groups each contribute a base branch from their summarized table.
 */
function multiGroupAssemblySQL(
  plan: TablePlan,
  allMetrics: MetricPlan[],
  bftMetrics: MetricPlan[],
  sumGroups: GrainGroup[],
  sm: SourceMapping,
  prefix: string,
  placeholderLabel: string
): string {
  const branches: string[] = [];

  // BFT-grain base branch (from merged BFT pipeline, if it exists)
  if (bftMetrics.length > 0) {
    branches.push(groupBaseBranch(plan, {
      id: "bft", grain: plan.bftGrain, joinChain: plan.bftJoinChain,
      metrics: bftMetrics, needsSummarization: false,
    }, allMetrics, sm, `${prefix}_weighted`, placeholderLabel));

    // Placeholder branches for BFT-grain metrics
    for (const metric of bftMetrics) {
      if (metric.nature === "non-additive") continue;

      const hasElimDims = metric.propagatedDimensions.some((d) => d.strategy === "elimination");
      const hasAllocDims = metric.propagatedDimensions.some((d) => d.strategy === "allocation");
      const hasReserveDims = metric.reserveDimensions.length > 0;
      const hasPropagation = hasElimDims || hasAllocDims;

      if (!hasPropagation && !hasReserveDims) continue;

      if (hasReserveDims) {
        if (hasPropagation) {
          branches.push(propagationDataBranch(plan, metric, allMetrics, sm, prefix, placeholderLabel));
        } else {
          branches.push(reserveBranch(plan, metric, allMetrics, sm, placeholderLabel));
        }
      }

      if (hasElimDims) {
        const elimDims = metric.propagatedDimensions.filter((d) => d.strategy === "elimination");
        for (const elimDim of elimDims) {
          branches.push(elimCorrectionBranch(plan, metric, elimDim, allMetrics, sm, prefix, placeholderLabel));
        }
      }
    }
  }

  // Summarization groups contribute base branches from their summarized tables
  for (const group of sumGroups) {
    const gPrefix = `${prefix}_${group.id}`;
    branches.push(groupBaseBranch(plan, group, allMetrics, sm, `${gPrefix}_summarized`, placeholderLabel));
  }

  const unionAll = branches.join("\n\nUNION ALL\n\n");

  return [
    `${"-".repeat(71)}`,
    `-- Step 3: Assemble final table`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${q(plan.tableName)} AS`,
    "",
    unionAll + ";",
  ].join("\n");
}

/**
 * Base branch for one grain group in a multi-group table.
 * Outputs real entity columns for entities in the group's grain,
 * placeholder labels for BFT entities not in the group's grain,
 * metric expressions for the group's metrics, and 0 for other metrics.
 */
function groupBaseBranch(
  plan: TablePlan,
  group: GrainGroup,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  sourceTable: string,
  label: string
): string {
  const groupGrainSet = new Set(group.grain);
  const groupMetricNames = new Set(group.metrics.map((m) => m.name));
  const lines: string[] = [`-- ${group.id} base rows`];
  lines.push("SELECT");

  const cols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    const nameCol = q(entityName.toLowerCase() + "_name");
    if (groupGrainSet.has(entityName)) {
      cols.push(q(es.idColumn));
      cols.push(nameCol);
    } else {
      cols.push(`NULL AS ${q(es.idColumn)}`);
      cols.push(`'${label}' AS ${nameCol}`);
    }
  }

  for (const metric of allMetrics) {
    if (groupMetricNames.has(metric.name)) {
      // This metric belongs to this group
      if (group.needsSummarization) {
        cols.push(q(metric.name));
        if (metric.nature === "non-additive") {
          cols.push(q(metric.name + "_weight"));
        }
      } else if (metric.nature === "non-additive") {
        cols.push(q(metric.name));
        cols.push(sumOverSumWeightExpr(metric) + ` AS ${q(metric.name + "_weight")}`);
      } else if (metric.reserveDimensions.length > 0) {
        cols.push(`0.0 AS ${q(metric.name)}`);
      } else {
        cols.push(allocationExpr(metric, sm) + ` AS ${q(metric.name)}`);
      }
    } else {
      // Metric from another group: 0
      cols.push(`0.0 AS ${q(metric.name)}`);
      if (metric.nature === "non-additive") {
        cols.push(`0 AS ${q(metric.name + "_weight")}`);
      }
    }
  }

  lines.push(cols.map((c) => `    ${c}`).join(",\n"));
  lines.push(`FROM ${q(sourceTable)}`);
  return lines.join("\n");
}

function allocationExpr(metric: MetricPlan, sm: SourceMapping): string {
  const allocDims = metric.propagatedDimensions
    .filter((d) => d.strategy === "allocation")
    .sort((a, b) => (a.hopIndex ?? 0) - (b.hopIndex ?? 0));

  let expr = `${q(metric.name)} * 1.0`;
  for (const dim of allocDims) {
    expr += ` / ${q(dim.relationship.toLowerCase() + "_count")}`;
  }
  return expr;
}

function sumOverSumWeightExpr(metric: MetricPlan): string {
  const dim = metric.propagatedDimensions.find((d) => d.strategy === "sum_over_sum");
  if (!dim) return "1.0";
  return `1.0 / ${q(dim.relationship.toLowerCase() + "_count")}`;
}

/**
 * Reserve branch: one row per home entity value, all foreign = placeholder.
 */
function reserveBranch(
  plan: TablePlan,
  metric: MetricPlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  label: string
): string {
  const home = homeEntity(metric);
  const homeEs = sm.entities[home];
  const lines: string[] = [`-- Reserve placeholder rows for ${metric.name}`];
  lines.push("SELECT");

  const cols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    const nameCol = q(entityName.toLowerCase() + "_name");
    if (entityName === home) {
      cols.push(q(es.idColumn));
      cols.push(`${q(es.labelColumn)} AS ${nameCol}`);
    } else {
      cols.push(`NULL AS ${q(es.idColumn)}`);
      cols.push(`'${label}' AS ${nameCol}`);
    }
  }

  for (const m of allMetrics) {
    if (m.name === metric.name) {
      cols.push(`${q(m.sourceColumn)} * 1.0 AS ${q(m.name)}`);
    } else {
      cols.push(`0.0 AS ${q(m.name)}`);
      if (m.nature === "non-additive") {
        cols.push(`0 AS ${q(m.name + "_weight")}`);
      }
    }
  }

  lines.push(cols.map((c) => `    ${c}`).join(",\n"));
  lines.push(`FROM ${q(homeEs.table)}`);
  return lines.join("\n");
}

/**
 * Propagation data branch: for metrics with reserve dimensions that also
 * have propagation (elimination or allocation). SELECT DISTINCT from the
 * weighted table, with real values for compute-grain entities and
 * placeholders for reserve entities.
 */
function propagationDataBranch(
  plan: TablePlan,
  metric: MetricPlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string,
  label: string
): string {
  const computeGrainSet = new Set(metric.computeGrain);
  const lines: string[] = [`-- ${metric.name} propagation data rows`];
  lines.push("SELECT DISTINCT");

  const cols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    const nameCol = q(entityName.toLowerCase() + "_name");
    if (computeGrainSet.has(entityName)) {
      cols.push(q(es.idColumn));
      cols.push(nameCol);
    } else {
      cols.push(`NULL AS ${q(es.idColumn)}`);
      cols.push(`'${label}' AS ${nameCol}`);
    }
  }

  for (const m of allMetrics) {
    if (m.name === metric.name) {
      cols.push(allocationExpr(metric, sm) + ` AS ${q(m.name)}`);
    } else {
      cols.push(`0.0 AS ${q(m.name)}`);
      if (m.nature === "non-additive") {
        cols.push(`0 AS ${q(m.name + "_weight")}`);
      }
    }
  }

  lines.push(cols.map((c) => `    ${c}`).join(",\n"));
  lines.push(`FROM ${q(prefix + "_weighted")}`);
  return lines.join("\n");
}

/**
 * Elimination correction branch: one row per home entity value.
 * Uses COUNT(DISTINCT target_id) from the base table to compute the
 * correction offset, so it works correctly regardless of reserve dims.
 */
function elimCorrectionBranch(
  plan: TablePlan,
  metric: MetricPlan,
  elimDim: DimensionStrategy,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string,
  label: string
): string {
  const elimTarget = sm.entities[elimDim.entity];
  const elimHopIndex = elimDim.hopIndex ?? 0;

  // Anchor entities: home grain + all propagated entities from earlier hops
  const anchorSet = new Set<string>(metric.home.grain);
  for (const d of metric.propagatedDimensions) {
    if (d.strategy === "reserve") continue;
    if ((d.hopIndex ?? 0) < elimHopIndex) {
      anchorSet.add(d.entity);
    }
  }

  const lines: string[] = [`-- ${metric.name} elimination correction (hop ${elimHopIndex})`];
  lines.push("SELECT");

  const cols: string[] = [];
  const groupCols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    const nameCol = q(entityName.toLowerCase() + "_name");
    if (anchorSet.has(entityName)) {
      cols.push(q(es.idColumn));
      cols.push(nameCol);
      groupCols.push(q(es.idColumn));
      groupCols.push(nameCol);
    } else {
      cols.push(`NULL AS ${q(es.idColumn)}`);
      cols.push(`'${label}' AS ${nameCol}`);
    }
  }

  for (const m of allMetrics) {
    if (m.name === metric.name) {
      cols.push(`${q(m.name)} * (1 - COUNT(DISTINCT ${q(elimTarget.idColumn)})) AS ${q(m.name)}`);
    } else {
      cols.push(`0 AS ${q(m.name)}`);
      if (m.nature === "non-additive") {
        cols.push(`0 AS ${q(m.name + "_weight")}`);
      }
    }
  }

  lines.push(cols.map((c) => `    ${c}`).join(",\n"));

  groupCols.push(q(metric.name));
  lines.push(`FROM ${q(prefix + "_base")}`);
  lines.push(`GROUP BY ${groupCols.join(", ")}`);

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Validation queries
// ---------------------------------------------------------------------------

function validationSQL(plan: TablePlan, allMetrics: MetricPlan[], sm: SourceMapping): string {
  const checks: string[] = [];
  checks.push(`${"-".repeat(71)}`);
  checks.push(`-- Validation`);
  checks.push(`${"-".repeat(71)}`);

  const hasSummarization = plan.grainGroups.some((g) => g.needsSummarization);
  let n = 1;

  // Determine if time is being summarized out of this table
  const bftGrainSet = new Set(plan.bftGrain);
  const summarizesTime = plan.timePlan != null && hasSummarization &&
    plan.grainGroups.some((g) => g.needsSummarization &&
      g.grain.some((e) => plan.timePlan!.timeDerivedEntities.has(e) && !bftGrainSet.has(e)));

  // V: SUM check for each additive metric
  for (const metric of allMetrics) {
    if (metric.nature === "non-additive") continue;
    // Stock metrics with time summarized out won't match source SUM (intentionally)
    if (metric.stock && summarizesTime) continue;

    const home = homeEntity(metric);
    // For relationship metrics, the source table is the junction table
    const sourceTable = metric.home.kind === "relationship"
      ? sm.relationships[metric.home.name].table
      : sm.entities[home].table;

    checks.push("");
    checks.push(`-- V${n}: SUM(${metric.name}) matches source`);
    checks.push(
      `SELECT 'V${n} ${metric.name}_sum' AS test,`,
      `       CASE WHEN ABS(SUM(${q(metric.name)}) - (SELECT SUM(${q(metric.sourceColumn)}) FROM ${q(sourceTable)})) < 0.01`,
      `            THEN 'PASS' ELSE 'FAIL: ' || SUM(${q(metric.name)}) END AS result`,
      `FROM ${q(plan.tableName)};`
    );
    n++;
  }

  // V: Per-entity SUM check for allocated metrics (only when no summarization)
  if (!hasSummarization) {
    for (const metric of allMetrics) {
      const hasAllocDims = metric.propagatedDimensions.some((d) => d.strategy === "allocation");
      if (!hasAllocDims || metric.reserveDimensions.length > 0) continue;

      const home = homeEntity(metric);
      const homeEs = sm.entities[home];
      const sourceTable = metric.home.kind === "relationship"
        ? sm.relationships[metric.home.name].table
        : homeEs.table;

      if (metric.home.kind === "relationship") {
        // For relationship metrics, per-home-entity check doesn't apply the same way
        // (the source is junction rows, not entity rows). Skip for now.
        continue;
      }

      checks.push("");
      checks.push(`-- V${n}: ${metric.name} per ${home} sums to original`);
      checks.push(
        `SELECT 'V${n} ${metric.name}_per_${home.toLowerCase()}' AS test,`,
        `       CASE WHEN COUNT(*) = 0 THEN 'PASS'`,
        `            ELSE 'FAIL: ' || COUNT(*) || ' with wrong sum' END AS result`,
        `FROM (`,
        `    SELECT t.${q(homeEs.idColumn)}, ABS(SUM(t.${q(metric.name)}) - s.${q(metric.sourceColumn)}) AS err`,
        `    FROM ${q(plan.tableName)} t`,
        `    JOIN ${q(homeEs.table)} s ON t.${q(homeEs.idColumn)} = s.${q(homeEs.idColumn)}`,
        `    GROUP BY t.${q(homeEs.idColumn)}, s.${q(metric.sourceColumn)}`,
        `    HAVING ABS(SUM(t.${q(metric.name)}) - s.${q(metric.sourceColumn)}) > 0.01`,
        `);`
      );
      n++;
    }
  }

  // V: Sum/Sum weight check (only for metrics at their natural grain —
  // propagated non-additive metrics have weights partitioned differently)
  for (const metric of allMetrics) {
    if (metric.nature !== "non-additive") continue;
    const hasPropagation = metric.propagatedDimensions.some((d) => d.strategy !== "reserve");
    if (hasPropagation) continue;

    const home = homeEntity(metric);
    const homeEs = sm.entities[home];
    checks.push("");
    checks.push(`-- V${n}: ${metric.name}_weight sums to 1.0 per ${home}`);
    checks.push(
      `SELECT 'V${n} ${metric.name}_weights' AS test,`,
      `       CASE WHEN COUNT(*) = 0 THEN 'PASS'`,
      `            ELSE 'FAIL: ' || COUNT(*) || ' with bad weights' END AS result`,
      `FROM (`,
      `    SELECT ${q(homeEs.idColumn)}, ABS(SUM(${q(metric.name + "_weight")}) - 1.0) AS err`,
      `    FROM ${q(plan.tableName)}`,
      `    WHERE ${q(homeEs.idColumn)} IS NOT NULL`,
      `    GROUP BY ${q(homeEs.idColumn)}`,
      `    HAVING ABS(SUM(${q(metric.name + "_weight")}) - 1.0) > 0.001`,
      `);`
    );
    n++;
  }

  return checks.join("\n");
}

// ---------------------------------------------------------------------------
// Run script
// ---------------------------------------------------------------------------

function generateRunScript(tableNames: string[]): string {
  // Build file list with numbered prefixes matching emitFiles output
  const sqlFiles = [
    "00_load_data.sql",
    ...tableNames.map((n, i) => `${String(i + 1).padStart(2, "0")}_${n}.sql`),
  ];
  const fileListPy = sqlFiles
    .map((f) => `os.path.join(script_dir, '${f}')`)
    .join(", ");

  // Use a heredoc with stdin arg to pass SCRIPT_DIR cleanly into python
  return `#!/bin/bash
# Generated by bft-maker
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Running BFT SQL..."
python3 - "$SCRIPT_DIR" <<'PYEOF'
import duckdb, os, sys

script_dir = sys.argv[1]
con = duckdb.connect()
files = [${fileListPy}]
all_pass = True
for f in files:
    print(f'\\n=== {f} ===')
    sql = open(f).read()
    for stmt in [s.strip() for s in sql.split(';') if s.strip()]:
        lines = [l for l in stmt.split('\\n') if l.strip() and not l.strip().startswith('--')]
        if not lines:
            continue
        result = con.execute(stmt)
        if lines[0].strip().split()[0].upper() == 'SELECT':
            for row in result.fetchall():
                cols = [d[0] for d in result.description]
                d = dict(zip(cols, row))
                status = 'PASS' if 'PASS' in str(d.get('result', '')) else 'FAIL'
                if status == 'FAIL':
                    all_pass = False
                print(f"  {d['test']}: {d['result']}")
print()
if all_pass:
    print('All validations passed.')
else:
    print('SOME VALIDATIONS FAILED')
    sys.exit(1)
PYEOF
`;
}
