import type { Manifest } from "../manifest/types.js";
import type {
  TablePlan,
  MetricPlan,
  SourceMapping,
  GeneratedOutput,
  GrainGroup,
  JoinLink,
} from "./types.js";
import { defaultSourceMapping } from "./planner.js";
import { planAll } from "./planner.js";

export interface GenerateOptions {
  sourceMapping?: SourceMapping;
  /** Directory containing source CSV files (used in load SQL). Default: "." */
  dataDir?: string;
}

/**
 * Generate all SQL for a manifest.
 */
export function generate(manifest: Manifest, options?: GenerateOptions): GeneratedOutput {
  const sm = options?.sourceMapping ?? defaultSourceMapping(manifest);
  const dataDir = options?.dataDir ?? ".";
  const plans = planAll(manifest, sm);

  const loadDataSQL = generateLoadData(manifest, sm, dataDir);
  const tables = plans.map((plan) => ({
    name: plan.tableName,
    sql: generateTableSQL(plan, manifest, sm),
  }));
  const runScript = generateRunScript(tables.map((t) => t.name));

  return { loadDataSQL, tables, runScript };
}

// ---------------------------------------------------------------------------
// Load data
// ---------------------------------------------------------------------------

function generateLoadData(manifest: Manifest, sm: SourceMapping, dataDir: string): string {
  const lines = ["-- Generated by bft-maker", "-- Load source data\n"];
  for (const entity of manifest.entities) {
    const es = sm.entities[entity.name];
    lines.push(
      `CREATE OR REPLACE TABLE ${es.table} AS`,
      `SELECT * FROM read_csv_auto('${dataDir}/${es.table}.csv');\n`
    );
  }
  for (const rel of manifest.relationships) {
    const rs = sm.relationships[rel.name];
    lines.push(
      `CREATE OR REPLACE TABLE ${rs.table} AS`,
      `SELECT * FROM read_csv_auto('${dataDir}/${rs.table}.csv');\n`
    );
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Per-table SQL
// ---------------------------------------------------------------------------

function generateTableSQL(plan: TablePlan, manifest: Manifest, sm: SourceMapping): string {
  const sections: string[] = [];
  const prefix = tablePrefix(plan.tableName);
  const label = manifest.placeholder_labels?.reserve ?? "<Unallocated>";
  const allMetrics = plan.grainGroups.flatMap((g) => g.metrics);

  sections.push(headerComment(plan, sm));

  // When there's one grain group whose grain matches the BFT grain,
  // generate the standard 3-step SQL. When summarization is needed,
  // generate at the compute grain then summarize down.
  const group = plan.grainGroups[0];

  if (!group.needsSummarization) {
    // Standard path: base join at BFT grain
    sections.push(baseJoinSQL(plan.bftGrain, plan.bftJoinChain, allMetrics, sm, prefix));
    sections.push(weightedSQL(group, sm, prefix));
    sections.push(assemblySQL(plan, allMetrics, sm, prefix, label));
  } else {
    // Summarization path: base join at compute grain, summarize down
    sections.push(baseJoinSQL(group.grain, group.joinChain, allMetrics, sm, prefix));
    sections.push(weightedSQL(group, sm, prefix));
    sections.push(summarizationSQL(plan, group, allMetrics, sm, prefix));
    sections.push(assemblySQL(plan, allMetrics, sm, prefix, label));
  }

  sections.push(validationSQL(plan, allMetrics, sm));

  return sections.join("\n\n");
}

function tablePrefix(tableName: string): string {
  // student_experience → se, department_financial → df
  return tableName
    .split("_")
    .map((w) => w[0])
    .join("");
}

// ---------------------------------------------------------------------------
// Header comment
// ---------------------------------------------------------------------------

function headerComment(plan: TablePlan, sm: SourceMapping): string {
  const lines = [`-- ${plan.tableName}.sql`, `-- Generated by bft-maker`];
  lines.push(`-- BFT table: ${plan.bftGrain.join(" x ")}`);
  lines.push(`-- Metrics:`);
  const allMetrics = plan.grainGroups.flatMap((g) => g.metrics);
  for (const m of allMetrics) {
    const dimDesc = m.propagatedDimensions
      .map((d) => `${d.strategy} for ${d.entity}`)
      .join(", ");
    lines.push(`--   ${m.name} (${m.home.name}) ${dimDesc}`);
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Step 1: Base grain join
// ---------------------------------------------------------------------------

function entityAlias(entityName: string): string {
  return entityName.toLowerCase().slice(0, 1);
}

function junctionAlias(relName: string): string {
  return relName.toLowerCase().slice(0, 1);
}

/** Get the primary home entity for a metric (first grain entity). */
function homeEntity(metric: MetricPlan): string {
  return metric.home.grain[0];
}

function baseJoinSQL(
  grainEntities: string[],
  joinChain: JoinLink[],
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string
): string {
  const firstEntity = grainEntities[0];
  const fe = sm.entities[firstEntity];
  const firstAlias = entityAlias(firstEntity);

  // Track which junction tables are used (for relationship metrics)
  const junctionAliasMap = new Map<string, string>();

  // SELECT columns
  const selectCols: string[] = [];
  for (const entityName of grainEntities) {
    const es = sm.entities[entityName];
    const alias = entityAlias(entityName);
    selectCols.push(`${alias}.${es.idColumn}`);
    selectCols.push(`${alias}.${es.labelColumn} AS ${entityName.toLowerCase()}_name`);
    // Entity metrics
    const entityMetrics = allMetrics.filter(
      (m) => m.home.kind === "entity" && m.home.grain[0] === entityName
    );
    for (const m of entityMetrics) {
      selectCols.push(`${alias}.${m.name}`);
    }
  }

  // JOIN chain — build it and collect junction aliases
  const aliases = new Map<string, string>();
  aliases.set(firstEntity, firstAlias);
  const joinLines: string[] = [];

  for (const link of joinChain) {
    const jAlias = junctionAlias(link.relationship);
    const toAlias = entityAlias(link.toEntity);
    aliases.set(link.toEntity, toAlias);
    junctionAliasMap.set(link.relationship, jAlias);

    const fromAlias = aliases.get(link.fromEntity)!;
    joinLines.push(
      `JOIN ${link.junctionTable} ${jAlias} ON ${fromAlias}.${sm.entities[link.fromEntity].idColumn} = ${jAlias}.${link.fromColumn}`
    );
    const toEs = sm.entities[link.toEntity];
    joinLines.push(
      `JOIN ${toEs.table} ${toAlias} ON ${toAlias}.${toEs.idColumn} = ${jAlias}.${link.toColumn}`
    );
  }

  // Relationship metrics — select from junction table alias
  for (const m of allMetrics) {
    if (m.home.kind === "relationship") {
      const jAlias = junctionAliasMap.get(m.home.name);
      if (jAlias) {
        selectCols.push(`${jAlias}.${m.name}`);
      }
    }
  }

  return [
    `${"-".repeat(71)}`,
    `-- Step 1: Base grain (${grainEntities.join(" x ")})`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${prefix}_base AS`,
    `SELECT`,
    selectCols.map((c) => `    ${c}`).join(",\n"),
    `FROM ${fe.table} ${firstAlias}`,
    joinLines.join("\n") + ";",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Step 2: Weights (window functions for allocation / sum_over_sum)
// ---------------------------------------------------------------------------

function weightedSQL(group: GrainGroup, sm: SourceMapping, prefix: string): string {
  const weightExprs = collectWeights(group, sm);
  if (weightExprs.length === 0) {
    // No weights needed — just alias base as weighted
    return [
      `${"-".repeat(71)}`,
      `-- Step 2: No weights needed`,
      `${"-".repeat(71)}`,
      `CREATE OR REPLACE TABLE ${prefix}_weighted AS`,
      `SELECT * FROM ${prefix}_base;`,
    ].join("\n");
  }

  return [
    `${"-".repeat(71)}`,
    `-- Step 2: Compute weights for allocation / sum_over_sum`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${prefix}_weighted AS`,
    `SELECT`,
    `    *,`,
    weightExprs.map((w) => `    ${w.expr} AS ${w.name}`).join(",\n"),
    `FROM ${prefix}_base;`,
  ].join("\n");
}

interface WeightExpr {
  name: string;
  expr: string;
}

function collectWeights(group: GrainGroup, sm: SourceMapping): WeightExpr[] {
  const weights: WeightExpr[] = [];
  const seen = new Set<string>();

  for (const metric of group.metrics) {
    if (metric.behavior === "pure_reserve" || metric.behavior === "pure_elimination" || metric.behavior === "mixed") {
      continue;
    }

    // For allocation and sum_over_sum: need count weights per hop
    const allocDims = metric.propagatedDimensions.filter(
      (d) => d.strategy === "allocation" || d.strategy === "sum_over_sum"
    );

    if (allocDims.length === 0) continue;

    // Sort by hopIndex to get the right partition expressions
    const sorted = [...allocDims].sort((a, b) => (a.hopIndex ?? 0) - (b.hopIndex ?? 0));

    // For relationship metrics, partition by all home grain entity ids
    const homePartitionCols = metric.home.grain.map((e) => sm.entities[e].idColumn);

    for (let i = 0; i < sorted.length; i++) {
      const dim = sorted[i];

      if (i === 0 && sorted.length > 1) {
        // First hop of multi-hop: COUNT(DISTINCT target_id) OVER (PARTITION BY home_ids)
        const targetEs = sm.entities[dim.entity];
        const weightName = `${dim.relationship.toLowerCase()}_count`;
        if (seen.has(weightName)) continue;
        seen.add(weightName);
        weights.push({
          name: weightName,
          expr: `COUNT(DISTINCT ${targetEs.idColumn}) OVER (PARTITION BY ${homePartitionCols.join(", ")})`,
        });
      } else if (i > 0) {
        // Subsequent hops: COUNT(*) OVER (PARTITION BY prev_entities)
        const partitionCols = [...homePartitionCols];
        for (let j = 0; j < i; j++) {
          partitionCols.push(sm.entities[sorted[j].entity].idColumn);
        }
        const weightName = `${dim.relationship.toLowerCase()}_count`;
        if (seen.has(weightName)) continue;
        seen.add(weightName);
        weights.push({
          name: weightName,
          expr: `COUNT(*) OVER (PARTITION BY ${partitionCols.join(", ")})`,
        });
      } else {
        // Single-hop allocation or sum_over_sum
        const weightName = `${dim.relationship.toLowerCase()}_count`;
        if (seen.has(weightName)) continue;
        seen.add(weightName);
        weights.push({
          name: weightName,
          expr: `COUNT(*) OVER (PARTITION BY ${homePartitionCols.join(", ")})`,
        });
      }
    }
  }

  return weights;
}

// ---------------------------------------------------------------------------
// Step 2.5: Summarization (GROUP BY to remove non-BFT entities)
// ---------------------------------------------------------------------------

function summarizationSQL(
  plan: TablePlan,
  group: GrainGroup,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string
): string {
  const bftGrainSet = new Set(plan.bftGrain);

  // GROUP BY columns: BFT grain entity ids and names
  const groupByCols: string[] = [];
  const selectCols: string[] = [];

  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    groupByCols.push(es.idColumn);
    groupByCols.push(`${entityName.toLowerCase()}_name`);
    selectCols.push(es.idColumn);
    selectCols.push(`${entityName.toLowerCase()}_name`);
  }

  // Metric expressions: SUM for allocated/eliminated, SUM for value and SUM for weight for sum_over_sum
  for (const metric of allMetrics) {
    if (metric.behavior === "fully_allocated") {
      // Allocation expression from the weighted table, then sum
      selectCols.push(`SUM(${allocationExpr(metric, sm)}) AS ${metric.name}`);
    } else if (metric.behavior === "sum_over_sum") {
      selectCols.push(`SUM(${metric.name}) AS ${metric.name}`);
      selectCols.push(`SUM(${sumOverSumWeightExpr(metric)}) AS ${metric.name}_weight`);
    } else if (metric.behavior === "pure_elimination") {
      selectCols.push(`SUM(${metric.name} * 1.0) AS ${metric.name}`);
    } else {
      selectCols.push(`SUM(${metric.name} * 1.0) AS ${metric.name}`);
    }
  }

  return [
    `${"-".repeat(71)}`,
    `-- Step 2.5: Summarize to BFT grain (${plan.bftGrain.join(" x ")})`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${prefix}_summarized AS`,
    `SELECT`,
    selectCols.map((c) => `    ${c}`).join(",\n"),
    `FROM ${prefix}_weighted`,
    `GROUP BY ${groupByCols.join(", ")};`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Step 3: Assembly (UNION ALL of base grain + placeholder branches)
// ---------------------------------------------------------------------------

function assemblySQL(
  plan: TablePlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string,
  placeholderLabel: string
): string {
  const branches: string[] = [];

  // Determine source table for base grain rows
  const hasSummarization = plan.grainGroups.some((g) => g.needsSummarization);
  const sourceTable = hasSummarization ? `${prefix}_summarized` : `${prefix}_weighted`;

  // Branch A: base grain rows
  branches.push(baseGrainBranch(plan, allMetrics, sm, sourceTable));

  // Placeholder branches for each metric (only when no summarization —
  // summarized tables already have the correct aggregation)
  if (!hasSummarization) {
    for (const metric of allMetrics) {
      if (metric.behavior === "fully_allocated" || metric.behavior === "sum_over_sum") {
        continue; // no placeholder rows needed
      }

      if (metric.behavior === "pure_reserve") {
        branches.push(reserveBranch(plan, metric, allMetrics, sm, placeholderLabel));
      } else if (metric.behavior === "pure_elimination") {
        branches.push(eliminationCorrectionBranch(plan, metric, allMetrics, sm, prefix, placeholderLabel));
      } else if (metric.behavior === "mixed") {
        // Elimination + reserve interaction
        branches.push(mixedElimDataBranch(plan, metric, allMetrics, sm, placeholderLabel));
        branches.push(mixedElimCorrectionBranch(plan, metric, allMetrics, sm, placeholderLabel));
      }
    }
  }

  const unionAll = branches.join("\n\nUNION ALL\n\n");

  return [
    `${"-".repeat(71)}`,
    `-- Step 3: Assemble final table`,
    `${"-".repeat(71)}`,
    `CREATE OR REPLACE TABLE ${plan.tableName} AS`,
    "",
    unionAll + ";",
  ].join("\n");
}

/**
 * Base grain branch: all real entity columns, metric expressions applied.
 */
function baseGrainBranch(
  plan: TablePlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  sourceTable: string
): string {
  const hasSummarization = plan.grainGroups.some((g) => g.needsSummarization);
  const lines: string[] = [`-- Base grain rows`];
  lines.push("SELECT");

  const cols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    cols.push(es.idColumn);
    cols.push(`${entityName.toLowerCase()}_name`);
  }

  for (const metric of allMetrics) {
    if (hasSummarization) {
      // Summarized table already has the right values
      cols.push(`${metric.name}`);
      if (metric.behavior === "sum_over_sum") {
        cols.push(`${metric.name}_weight`);
      }
    } else if (metric.behavior === "fully_allocated") {
      cols.push(allocationExpr(metric, sm) + ` AS ${metric.name}`);
    } else if (metric.behavior === "sum_over_sum") {
      cols.push(`${metric.name}`);
      cols.push(sumOverSumWeightExpr(metric) + ` AS ${metric.name}_weight`);
    } else {
      // pure_elimination where no dims are reserve: full value on base rows
      // pure_reserve or mixed: 0 on base rows
      if (metric.behavior === "pure_elimination") {
        cols.push(`${metric.name} * 1.0 AS ${metric.name}`);
      } else {
        cols.push(`0.0 AS ${metric.name}`);
      }
    }
  }

  lines.push(cols.map((c) => `    ${c}`).join(",\n"));
  lines.push(`FROM ${sourceTable}`);
  return lines.join("\n");
}

function allocationExpr(metric: MetricPlan, sm: SourceMapping): string {
  const allocDims = metric.propagatedDimensions
    .filter((d) => d.strategy === "allocation")
    .sort((a, b) => (a.hopIndex ?? 0) - (b.hopIndex ?? 0));

  let expr = `${metric.name} * 1.0`;
  for (const dim of allocDims) {
    expr += ` / ${dim.relationship.toLowerCase()}_count`;
  }
  return expr;
}

function sumOverSumWeightExpr(metric: MetricPlan): string {
  const dim = metric.propagatedDimensions.find((d) => d.strategy === "sum_over_sum");
  if (!dim) return "1.0";
  return `1.0 / ${dim.relationship.toLowerCase()}_count`;
}

/**
 * Reserve branch: one row per home entity value, all foreign = placeholder.
 */
function reserveBranch(
  plan: TablePlan,
  metric: MetricPlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  label: string
): string {
  const home = homeEntity(metric);
  const homeEs = sm.entities[home];
  const lines: string[] = [`-- Reserve placeholder rows for ${metric.name}`];
  lines.push("SELECT");

  const cols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    if (entityName === home) {
      cols.push(es.idColumn);
      cols.push(`${es.labelColumn} AS ${entityName.toLowerCase()}_name`);
    } else {
      cols.push(`NULL AS ${es.idColumn}`);
      cols.push(`'${label}' AS ${entityName.toLowerCase()}_name`);
    }
  }

  for (const m of allMetrics) {
    if (m.name === metric.name) {
      cols.push(`${m.name} * 1.0 AS ${m.name}`);
    } else {
      cols.push(`0.0 AS ${m.name}`);
      if (m.behavior === "sum_over_sum") {
        cols.push(`0 AS ${m.name}_weight`);
      }
    }
  }

  lines.push(cols.map((c) => `    ${c}`).join(",\n"));
  lines.push(`FROM ${homeEs.table}`);
  return lines.join("\n");
}

/**
 * Pure elimination correction branch: one row per home entity value.
 * foreign entity = placeholder, metric = value * (1 - N).
 */
function eliminationCorrectionBranch(
  plan: TablePlan,
  metric: MetricPlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  prefix: string,
  label: string
): string {
  const home = homeEntity(metric);
  const homeEs = sm.entities[home];
  const lines: string[] = [`-- Elimination correction rows for ${metric.name}`];
  lines.push("SELECT");

  const cols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    if (entityName === home) {
      cols.push(es.idColumn);
      cols.push(`${entityName.toLowerCase()}_name`);
    } else {
      cols.push(`NULL AS ${es.idColumn}`);
      cols.push(`'${label}' AS ${entityName.toLowerCase()}_name`);
    }
  }

  for (const m of allMetrics) {
    if (m.name === metric.name) {
      cols.push(`${m.name} * (1 - COUNT(*)) AS ${m.name}`);
    } else {
      cols.push(`0 AS ${m.name}`);
      if (m.behavior === "sum_over_sum") {
        cols.push(`0 AS ${m.name}_weight`);
      }
    }
  }

  lines.push(cols.map((c) => `    ${c}`).join(",\n"));

  const groupCols = [homeEs.idColumn, `${home.toLowerCase()}_name`, metric.name];
  lines.push(`FROM ${prefix}_base`);
  lines.push(`GROUP BY ${groupCols.join(", ")}`);

  return lines.join("\n");
}

/**
 * Mixed: elimination data rows. The metric appears on rows where
 * reserve-dimension entities are placeholder, but elimination-dimension
 * entities are real. Source is the enrollment join (not the full base grain).
 */
function mixedElimDataBranch(
  plan: TablePlan,
  metric: MetricPlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  label: string
): string {
  const home = homeEntity(metric);
  const homeEs = sm.entities[home];
  const elimDims = metric.propagatedDimensions.filter((d) => d.strategy === "elimination");

  // Outer SELECT: real columns for home + elimination entities, placeholder for reserve
  const outerCols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    if (entityName === home || elimDims.some((d) => d.entity === entityName)) {
      outerCols.push(es.idColumn);
      outerCols.push(`${entityName.toLowerCase()}_name`);
    } else {
      outerCols.push(`NULL AS ${es.idColumn}`);
      outerCols.push(`'${label}' AS ${entityName.toLowerCase()}_name`);
    }
  }
  for (const m of allMetrics) {
    if (m.name === metric.name) {
      outerCols.push(`${m.name} * 1.0 AS ${m.name}`);
    } else {
      outerCols.push(`0.0 AS ${m.name}`);
      if (m.behavior === "sum_over_sum") {
        outerCols.push(`0 AS ${m.name}_weight`);
      }
    }
  }

  // Subquery: join home entity to elimination-target entities via junction tables
  const subCols: string[] = [];
  const homeAlias = homeEs.table[0];
  // Elimination target entities
  for (const elimDim of elimDims) {
    const targetEs = sm.entities[elimDim.entity];
    const targetAlias = targetEs.table[0];
    subCols.push(`${targetAlias}.${targetEs.idColumn}`);
    subCols.push(`${targetAlias}.${targetEs.labelColumn} AS ${elimDim.entity.toLowerCase()}_name`);
  }
  // Home entity
  subCols.push(`${homeAlias}.${homeEs.idColumn}`);
  subCols.push(`${homeAlias}.${homeEs.labelColumn} AS ${home.toLowerCase()}_name`);
  subCols.push(`${homeAlias}.${metric.name}`);

  const subJoins: string[] = [];
  for (const elimDim of elimDims) {
    const relSource = sm.relationships[elimDim.relationship];
    const targetEs = sm.entities[elimDim.entity];
    const targetAlias = targetEs.table[0];
    const jAlias = relSource.table[0];
    subJoins.push(`    JOIN ${relSource.table} ${jAlias} ON ${targetAlias}.${targetEs.idColumn} = ${jAlias}.${relSource.columns[elimDim.entity]}`);
    subJoins.push(`    JOIN ${homeEs.table} ${homeAlias} ON ${homeAlias}.${homeEs.idColumn} = ${jAlias}.${relSource.columns[home]}`);
  }

  // First elimination target is the FROM table
  const firstTarget = sm.entities[elimDims[0].entity];
  const firstAlias = firstTarget.table[0];

  const lines = [
    `-- ${metric.name} elimination data rows`,
    `SELECT`,
    outerCols.map((c) => `    ${c}`).join(",\n"),
    `FROM (`,
    `    SELECT DISTINCT`,
    subCols.map((c) => `        ${c}`).join(",\n"),
    `    FROM ${firstTarget.table} ${firstAlias}`,
    ...subJoins,
    `)`,
  ];

  return lines.join("\n");
}

/**
 * Mixed: elimination correction rows. Both elimination and reserve
 * dimensions get placeholder labels.
 */
function mixedElimCorrectionBranch(
  plan: TablePlan,
  metric: MetricPlan,
  allMetrics: MetricPlan[],
  sm: SourceMapping,
  label: string
): string {
  const home = homeEntity(metric);
  const homeEs = sm.entities[home];
  const elimDims = metric.propagatedDimensions.filter((d) => d.strategy === "elimination");

  const lines: string[] = [`-- ${metric.name} elimination correction rows`];
  lines.push("SELECT");

  const cols: string[] = [];
  for (const entityName of plan.bftGrain) {
    const es = sm.entities[entityName];
    if (entityName === home) {
      cols.push(`c.${es.idColumn}`);
      cols.push(`c.${es.labelColumn} AS ${entityName.toLowerCase()}_name`);
    } else {
      cols.push(`NULL AS ${es.idColumn}`);
      cols.push(`'${label}' AS ${entityName.toLowerCase()}_name`);
    }
  }

  for (const m of allMetrics) {
    if (m.name === metric.name) {
      cols.push(`c.${m.name} * (1 - ec.${elimDims[0].relationship.toLowerCase()}_count) AS ${m.name}`);
    } else {
      cols.push(`0.0 AS ${m.name}`);
      if (m.behavior === "sum_over_sum") {
        cols.push(`0 AS ${m.name}_weight`);
      }
    }
  }

  lines.push(cols.map((c) => `    ${c}`).join(",\n"));

  // Join home entity table with enrollment counts
  const elimRel = sm.relationships[elimDims[0].relationship];
  const elimEntityCol = elimRel.columns[elimDims[0].entity];
  const homeCol = elimRel.columns[home];

  lines.push(`FROM ${homeEs.table} c`);
  lines.push(`JOIN (`);
  lines.push(`    SELECT ${homeCol}, COUNT(*) AS ${elimDims[0].relationship.toLowerCase()}_count`);
  lines.push(`    FROM ${elimRel.table}`);
  lines.push(`    GROUP BY ${homeCol}`);
  lines.push(`) ec ON c.${homeEs.idColumn} = ec.${homeCol}`);

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Validation queries
// ---------------------------------------------------------------------------

function validationSQL(plan: TablePlan, allMetrics: MetricPlan[], sm: SourceMapping): string {
  const checks: string[] = [];
  checks.push(`${"-".repeat(71)}`);
  checks.push(`-- Validation`);
  checks.push(`${"-".repeat(71)}`);

  const hasSummarization = plan.grainGroups.some((g) => g.needsSummarization);
  let n = 1;

  // V: SUM check for each additive metric
  for (const metric of allMetrics) {
    if (metric.nature === "non-additive") continue;

    const home = homeEntity(metric);
    // For relationship metrics, the source table is the junction table
    const sourceTable = metric.home.kind === "relationship"
      ? sm.relationships[metric.home.name].table
      : sm.entities[home].table;

    checks.push("");
    checks.push(`-- V${n}: SUM(${metric.name}) matches source`);
    checks.push(
      `SELECT 'V${n} ${metric.name}_sum' AS test,`,
      `       CASE WHEN ABS(SUM(${metric.name}) - (SELECT SUM(${metric.name}) FROM ${sourceTable})) < 0.01`,
      `            THEN 'PASS' ELSE 'FAIL: ' || SUM(${metric.name}) END AS result`,
      `FROM ${plan.tableName};`
    );
    n++;
  }

  // V: Per-entity SUM check for allocated metrics (only when no summarization)
  if (!hasSummarization) {
    for (const metric of allMetrics) {
      if (metric.behavior !== "fully_allocated") continue;

      const home = homeEntity(metric);
      const homeEs = sm.entities[home];
      const sourceTable = metric.home.kind === "relationship"
        ? sm.relationships[metric.home.name].table
        : homeEs.table;

      if (metric.home.kind === "relationship") {
        // For relationship metrics, per-home-entity check doesn't apply the same way
        // (the source is junction rows, not entity rows). Skip for now.
        continue;
      }

      checks.push("");
      checks.push(`-- V${n}: ${metric.name} per ${home} sums to original`);
      checks.push(
        `SELECT 'V${n} ${metric.name}_per_${home.toLowerCase()}' AS test,`,
        `       CASE WHEN COUNT(*) = 0 THEN 'PASS'`,
        `            ELSE 'FAIL: ' || COUNT(*) || ' with wrong sum' END AS result`,
        `FROM (`,
        `    SELECT t.${homeEs.idColumn}, ABS(SUM(t.${metric.name}) - s.${metric.name}) AS err`,
        `    FROM ${plan.tableName} t`,
        `    JOIN ${homeEs.table} s ON t.${homeEs.idColumn} = s.${homeEs.idColumn}`,
        `    GROUP BY t.${homeEs.idColumn}, s.${metric.name}`,
        `    HAVING ABS(SUM(t.${metric.name}) - s.${metric.name}) > 0.01`,
        `);`
      );
      n++;
    }
  }

  // V: Sum/Sum weight check
  for (const metric of allMetrics) {
    if (metric.behavior !== "sum_over_sum") continue;

    const home = homeEntity(metric);
    const homeEs = sm.entities[home];
    checks.push("");
    checks.push(`-- V${n}: ${metric.name}_weight sums to 1.0 per ${home}`);
    checks.push(
      `SELECT 'V${n} ${metric.name}_weights' AS test,`,
      `       CASE WHEN COUNT(*) = 0 THEN 'PASS'`,
      `            ELSE 'FAIL: ' || COUNT(*) || ' with bad weights' END AS result`,
      `FROM (`,
      `    SELECT ${homeEs.idColumn}, ABS(SUM(${metric.name}_weight) - 1.0) AS err`,
      `    FROM ${plan.tableName}`,
      `    WHERE ${homeEs.idColumn} IS NOT NULL`,
      `    GROUP BY ${homeEs.idColumn}`,
      `    HAVING ABS(SUM(${metric.name}_weight) - 1.0) > 0.001`,
      `);`
    );
    n++;
  }

  return checks.join("\n");
}

// ---------------------------------------------------------------------------
// Run script
// ---------------------------------------------------------------------------

function generateRunScript(tableNames: string[]): string {
  const lines = [
    `#!/bin/bash`,
    `# Generated by bft-maker`,
    `set -euo pipefail`,
    ``,
    `SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"`,
    `REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"`,
    `cd "$REPO_ROOT"`,
    ``,
  ];

  // Python runner (same approach as the hand-written run.sh)
  const fileList = [
    `'$SCRIPT_DIR/00_load_data.sql'`,
    ...tableNames.map((n) => `'$SCRIPT_DIR/${n}.sql'`),
  ];

  lines.push(`echo "Running BFT SQL..."`);
  lines.push(`python3 -c "`);
  lines.push(`import duckdb, sys`);
  lines.push(`con = duckdb.connect()`);
  lines.push(`files = [${fileList.join(", ")}]`);
  lines.push(`all_pass = True`);
  lines.push(`for f in files:`);
  lines.push(`    print(f'\\n=== {f} ===')`);
  lines.push(`    sql = open(f).read()`);
  lines.push(`    for stmt in [s.strip() for s in sql.split(';') if s.strip()]:`);
  lines.push(`        lines = [l for l in stmt.split('\\n') if l.strip() and not l.strip().startswith('--')]`);
  lines.push(`        if not lines: continue`);
  lines.push(`        result = con.execute(stmt)`);
  lines.push(`        if lines[0].strip().split()[0].upper() == 'SELECT':`);
  lines.push(`            for row in result.fetchall():`);
  lines.push(`                cols = [d[0] for d in result.description]`);
  lines.push(`                d = dict(zip(cols, row))`);
  lines.push(`                status = 'PASS' if 'PASS' in str(d.get('result','')) else 'FAIL'`);
  lines.push(`                if status == 'FAIL': all_pass = False`);
  lines.push(`                print(f\"  {d['test']}: {d['result']}\")`);
  lines.push(`print()`);
  lines.push(`if all_pass: print('All validations passed.')`);
  lines.push(`else: print('SOME VALIDATIONS FAILED'); sys.exit(1)`);
  lines.push(`"`);

  return lines.join("\n");
}
